### PR TITLE
Fixing deps

### PR DESCRIPTION
**Pull request by jeregrine**
Was referencing github when it should be referencing hex. Also added a lock file.

### CODE REVIEW

**Comment by jarednorman** [comment]
I don't think we should include the lock. Why'd you add it?

**Comment by jeregrine** [comment]
Isnt that the point of the lock to make sure everyone gets the same deps? :P I can remove it

**Comment by jarednorman** [comment]
The lock is usually checked in for applications but it's generally bad practice to lock down libraries. The deps in our `mix.exs` are specific enough. It doesn't matter what minor version of bugsnag or any of bugsnag's deps the end application wants to use, as long as it's `~> 1.0.0`.

**Comment by jeregrine** [comment]
@jarednorman I made the changes and loosened the requirement on bugnsag versions to just v1.

**Comment by jarednorman** [comment]
I think you want `~> 1.0`.

**Comment by jeregrine** [comment]
@jarednorman 1.0 wont match 1.1

**Comment by jarednorman** [comment]
Doesn't it work the same as it does in bundler, as in (from the bundler site), "`~> 2.1` is identical to `>= 2.1` and `< 3.0`"?

**Comment by jeregrine** [comment]
Updated.
https://github.com/elixir-lang/elixir/blob/34878f87af43c112682e9ee5a3a2af3b1272cf53/lib/elixir/lib/version.ex#L65

**Comment by jarednorman** [comment]
Thanks!

**Pull request merged**
