### PR TITLE
Don't report non-HTTP 5xx errors to Bugsnag

### PR DESCRIPTION
**Pull request by joelcrocker**
Exceptions are used in Phoenix for various HTTP 4xx user errors. 4xx status codes indicate a problem with the request, not an unhandled error on the server. As such, only exceptions that get rendered as HTTP 500s by Plug should be sent to Bugsnag.

### CODE REVIEW

**Comment by stephanos** [comment]
@jarednorman this has bitten us, too, recently. Would you consider merging it or is something holding you back?

**Comment by jarednorman** [comment]
There's conflicts, but if they are resolved I think I can merge this.

**Comment by jarednorman** [comment]
This project is currently without a maintainer for the moment. The person maintaining it for me stepped away a while back and I've not found anyone new to take it on. I'm currently very busy running a company and don't have time to give this the review it needs to be confident merging it.

If the conflicts are addressed and you're both confident in this solution then I can merge this, but I'm admittedly not working actively in Elixir and don't have the resources to properly review anything for now.

**Comment by bzmw** [comment]
Hey @nirev @jarednorman we see that a PR was merged last week, has the maintainer situation changed?

**Comment by jarednorman** [comment]
Yeah, we've moved the Elixir Bugsnag integrations to their own org and @nirev has taken over maintaining them. 😁

**Comment by bzmw** [comment]
Woot!
In that case, @nirev, can you take a look at this PR?

**Comment by nirev** [comment]
Absolutely. I was working on fixing CI, first. But it's high on my to-do list!

**Comment by nirev** [comment]
Since a long time has passed since this PR was opened, it now has more changes than originally intended.
I've extracted the changes and will merge #40 instead of this one. 

Thank you for the work @joelcrocker, sorry it took this long.

**Pull request closed without merging**
